package MouseSOM::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MouseSOM::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:mousesom',
        user => 'webuser',
        password => 'webuser',
        AutoCommit => q{1},
        host => q{172.18.0.2},
        port => q{3306},
    }
);

=head1 NAME

MouseSOM::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MouseSOM>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MouseSOM::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
